"""
Python script to create a grid basedon bounding box extents in decimanl degrees.
"""

# Module imports.
import sys
import argparse
import shapefile as shp
import math

# Module variables.


# Module Methods.


# Gather input parameters using argsparser.
helpDescription = "This script requires 6 arguments: minLong, minLat, maxLong, maxLat, cell size, output filename."
helpDescription += "The minX, minY, maxX and maxY should be in DD (decimal degrees)."
helpDescription += "The cell size should be in meters."
helpDescription += "The output file name must be a single word, combined words using underscores, or in double quotes."

parser = argparse.ArgumentParser(description=helpDescription)
parser.add_argument("minLong", help="The minimum Longitude (N/S or X) for the coordinate bounding box in DD (decimal degrees).", type=int)
parser.add_argument("minLat", help="The minimum Latitude (E/W or Y) for the coordinate bounding box in DD (decimal degrees).", type=int)
parser.add_argument("maxLong", help="The maximum Longitude (N/S or X) for the coordinate bounding box in DD (decimal degrees).", type=int)
parser.add_argument("maxLat", help="The maximum Latitude (E/W or Y) for the coordinate bounding box in DD (decimal degrees).", type=int)
parser.add_argument("cellSize", help="The cell size to create in meters.", type=int)
parser.add_argument("outputFilename", help="The base name of the output file(s) generated by the script.")
args = parser.parse_args()

if len (sys.argv) != 7 :    # 7 to include sys.argv[0].
    print("This script requires 6 parameters: minx, miny, maxx, maxy, cell size (in meters), output file name.")
    print("You passed in the following argumanets: ")
    for x in sys.argv:
        print("Argument: ", x)
    print("Exiting script.")
    sys.exit (1)


# Module.

print('START :: ', sys.argv[0])
for arg in sys.argv:
    print('parameter :: ' + arg, sys.argv[arg])



"""
Latitude

When looking at a map, latitude lines run horizontally.
Latitude lines are also known as parallels since they are parallel and are an equal distant from each other.
Each degree of latitude is approximately 69 miles (111 km) apart; there is a variation due to the fact that the earth is not a perfect sphere but an oblate ellipsoid (slightly egg-shaped).
To remember latitude, imagine them as the horizontal rungs of a ladder ("ladder-tude").
Degrees latitude are numbered from 0° to 90° north and south.
Zero degrees is the equator, the imaginary line which divides our planet into the northern and southern hemispheres.
90° north is the North Pole and 90° south is the South Pole.

Longitude

The vertical longitude lines are also known as meridians.
They converge at the poles and are widest at the equator (about 69 miles or 111 km apart).
Zero degrees longitude is located at Greenwich, England (0°).
The degrees continue 180° east and 180° west where they meet and form the International Date Line in the Pacific Ocean.
Greenwich, the site of the British Royal Greenwich Observatory, was established as the site of the prime meridian by an international conference in 1884.

Summary

Latitude (parallels) [horizontal rings eg. "ladder-tude"]
Longitude (meridians) [vertical lines]

Which is X, which is Y?

In ESRI, Lat = Y Long = X

It's easy to get backwards.
On a standard north facing map, latitude is represented by horizontal lines, which go up and down (North and South) the Y axis.
Its easy to think that since they are horizontal lines, they would be on the x axis, but they are not.
So similarly, the X axis is Longitude, as the values shift left to right (East and West) along the X axis.
Confusing for the same reason since on a north facing map, these lines are vertical.

DMS vs DD

The degrees, minutes, seconds (DMS) coordinate values need to be convert to decimal degrees (dd) before calculation.
http://www.rapidtables.com/convert/number/degrees-to-degrees-minutes-seconds.htm
http://www.rapidtables.com/convert/number/degrees-minutes-seconds-to-degrees.htm

How to convert decimal degrees to degrees,minutes,seconds

One degree (°) is equal to 60 minutes (') and equal to 3600 seconds ("):
    1° = 60' = 3600"
The integer degrees (d) are equal to the integer part of the decimal degrees (dd):
    d = integer(dd)
The minutes (m) are equal to the integer part of the decimal degrees (dd) minus integer degrees (d) times 60:
    m = integer((dd - d) × 60)
The seconds (s) are equal to the decimal degrees (dd) minus integer degrees (d) minus minutes (m) divided by 60 times 3600:
    s = (dd - d - m/60) × 3600

Example:
Convert 30.263888889° angle to degrees,minutes,seconds:
    d = integer(30.263888889°) = 30°
    m = integer((dd - d) × 60) = 15'
    s = (dd - d - m/60) × 3600 = 50"
Result:
    30.263888889° = 30° 15' 50"
"""
